### ISSUE TITLE
how can I use this with the latest sails v.0.10 ?

### ISSUE THREAD

**Issue by koraysels** [jmtexier/sails-generate-views-handlebars#1]
I have a lot of issues trying to get handlebars to run with the latest version of sails.. even with this generator.. I keep having errors relatied to the partial sthat do not work etc.. 

```
Error rendering view at :: [MyPath]/app/views/homepage
error: with layout located at :: undefined
error: The partial links could not be found
error: Sent 500 ("Server Error") response
error: The partial links could not be found
```

I really want to use handlebars and not EJS :( maybe anybody can help me ?

**Comment by dmitriy-01** [comment]
To fix this you need to modify `config/views.js`
and change `layout: 'layout'` to `layout: 'layouts/layout',` - to load views/layouts/layout.handlebars
and add one line after this to make partials work:
`partials: 'partials'`

So it will look like this:

``` javascript
module.exports.views = {
    engine: 'handlebars',
    layout: 'layouts/layout',
    partials: 'partials'
};
```

**Comment by yannickmodahgouez** [comment]
Thanks I had the same issue !

**Comment by dmitriy-01** [comment]
No problem - I have also created a Sails Boilerplate with Handlebars support and some other features, if you need something to start with: https://github.com/websquared/sails-boilerplate

**Comment by yannickmodahgouez** [comment]
looks great ! thanx @websquared

**Comment by jmtexier** [comment]
@yannickmodahgouez  @websquared @koraysels - FYI, I've submitted a PR https://github.com/balderdashy/sails-generate-backend/pull/9 in order to support layout and partials out of the box.

`sails new foobar --template=handlebars` works properly once you have `npm install sails-generate-views-handlebars` (now published as an [npm package](https://www.npmjs.org/package/sails-generate-views-handlebars) thanks to yannick)

**Comment by jmtexier** [comment]
PR was merged
